In [48]:
import pandas as pd
import requests
import json
import time

In [49]:
df_source = pd.read_json("best_cities_france.json")
df_source = df_source.rename(columns={0: "city"})
df_source.head()

                city
0  Mont Saint Michel
1            St Malo
2             Bayeux
3           Le Havre
4              Rouen

In [50]:
df = df_source.copy()
for index, row in df.iterrows():
    print(index, row["city"])
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'}
    res = requests.get(f"https://nominatim.openstreetmap.org/search?q={row['city']},France&format=json", headers=headers)
    city = res.json()[0]
    df.loc[index, "lat"] = city["lat"]
    df.loc[index, "lon"] = city["lon"]
    time.sleep(1)
df.head()

0 Mont Saint Michel
1 St Malo
2 Bayeux
3 Le Havre
4 Rouen
5 Paris
6 Amiens
7 Lille
8 Strasbourg
9 Chateau du Haut Koenigsbourg
10 Colmar
11 Eguisheim
12 Besancon
13 Dijon
14 Annecy
15 Grenoble
16 Lyon
17 Gorges du Verdon
18 Bormes les Mimosas
19 Cassis
20 Marseille
21 Aix en Provence
22 Avignon
23 Uzes
24 Nimes
25 Aigues Mortes
26 Saintes Maries de la mer
27 Collioure
28 Carcassonne
29 Ariege
30 Toulouse
31 Montauban
32 Biarritz
33 Bayonne
34 La Rochelle

                city         lat         lon
0  Mont Saint Michel  48.6359541  -1.5114600
1            St Malo  48.6495180  -2.0260409
2             Bayeux  49.2764624  -0.7024738
3           Le Havre  49.4938975   0.1079732
4              Rouen  49.4404591   1.0939658

In [ ]:
for index, row in df.iterrows():
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'}
    res_weather = requests.get(f"https://api.openweathermap.org/data/2.5/onecall?lat={row['lat']}&lon={row['lon']}&exclude=current,minutely,hourly,alerts&appid=4656ed7337e689999007412af6a4dafe", headers=headers)
    print(res_weather.json())
    # Stock score for temperature, rain prob, cloud prob, win speed
    # Scale all to the same scale
    # Calculate Score = (Température * Coeff) - (Pluie * Coeff) - (Nuages * Coeff)
        # Define the coef based on my own importance
    break

{'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}